application: staging-api-getunseen
module: fb-canvas
version: 1
runtime: go
api_version: go1

instance_class: F2

handlers:

  - url: /components
    static_dir: public/js/components

  - url: /bower_components
    static_dir: public/js/bower_components

  - url: /(.*\.json)$
    static_files: public/\1
    upload: public/.*\.(json)$

  - url: /$
    static_files: public/index.html
    upload: public/.*\.(html)$

  - url: /.*
    script: _go_app
    secure: always